name: 'Build GCC'
description: 'Configure, build, and generate GCC dist'
inputs:
  branch:
    description: 'Branch to build from'
    required: true
  dist-name:
    description: 'Dist package name'
    required: true
  config-args:
    description: 'Configure command line arguments'
    required: true
outputs:
  dist-dir:
    description: 'Output dist directory'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{inputs.branch}}
    - ${{inputs.dist-name}}
    - ${{inputs.config-args}}
