name: 'Storage downlaod'
description: 'Download a file or directory from private storage'
inputs:
  name:
    description: 'Storage id of the package to download'
    required: true
  storage-url:
    description: 'Url of private storage'
    required: true
  path:
    description: 'Path were the package is downloaded'
    required: false
    default: './'
  username:
    description: 'Username for private storage access'
    required: false
    default: ''
  password:
    description: 'Password for private storage access'
    required: false
    default: ''
  storage-path:
    description: 'Custom storage path'
    required: false
    default: ''
runs:
  using: 'composite'
  steps:
    - name: Download package
      id: dwn
      shell: bash
      run: |
        set -e
        if [[ ! -z "${{inputs.storage-path}}" ]]; then
          PKG_URL="${{inputs.storage-url}}/${{inputs.storage-path}}/${{inputs.name}}.tar.xz"
        else
          PKG_URL="${{inputs.storage-url}}/${{github.ref}}/${{inputs.name}}.tar.xz"
        fi
        echo "Downloading from $PKG_URL to ${{inputs.path}}"
        mkdir -p "${{inputs.path}}"
        if [[ -z '${{inputs.username}}' ]]; then
          curl -L "$PKG_URL" --fail | pxz -dc | tar -C "${{inputs.path}}" -xf -;
        else
          curl -u '${{inputs.username}}':'${{inputs.password}}' -L "$PKG_URL" --fail | pxz -dc | tar -C "${{inputs.path}}" -xf -;
        fi
        chmod -R g+w "${{inputs.path}}"
        echo "Content restored in '${{inputs.path}}'"
