name: Build AppImage

on:
  workflow_dispatch:
    inputs:
      package-name:
        description: "Bambu AppImage name"
        required: true
        default: "bambu-gcc7_clang11"
      branch:
        description: "Repository branch to build from"
        required: false
        default: "main"
      compilers:
        description: "Comma separated list of compilers to include"
        required: true
        default: "gcc-7,clang-12"
      build-compiler:
        description: "Compiler used to build bambu (if not already included in compilers)"
        required: false
        default: "gcc-8"
      configure:
        description: "Bambu configuration options"
        required: true
        default: "--enable-glpk --enable-flopoco --enable-opt --with-opt-level=2 --enable-release CC=gcc-8 CXX=g++-8 --with-gcc8=/bin/false"

  workflow_call:
    inputs:
      package-name:
        description: "Bambu AppImage package name"
        required: true
        type: string
      compilers:
        description: "Comma separated list of compilers to include"
        required: false
        type: string
        default: "gcc-7,clang-12"
      build-compiler:
        description: "Compiler used to build bambu (if not already included in compilers)"
        required: false
        type: string
        default: "gcc-8"
      configure:
        description: "Bambu configuration options"
        required: false
        type: string
        default: "--enable-glpk --enable-flopoco --enable-opt --with-opt-level=2 --enable-release CC=gcc-8 CXX=g++-8 --with-gcc8=/bin/false"
    secrets:
      CI_STORAGE_URL:
        required: true
      CI_STORAGE_USER:
        required: true
      CI_STORAGE_TOKEN:
        required: true
    outputs:
      package-name: ${{inputs.package-name}}

env:
  compilers: ${{inputs.compilers}}${{github.event.inputs.compilers}}
  build-compiler: ${{inputs.build-compiler}}${{github.event.inputs.build-compiler}}
  configure: ${{inputs.configure}}${{github.event.inputs.configure}}
  compilers-dist-url: https://release.bambuhls.eu:8080/compiler
  storage-url: ${{secrets.CI_STORAGE_URL}}
  storage-user: ${{secrets.CI_STORAGE_USER}}
  storage-token: ${{secrets.CI_STORAGE_TOKEN}}
  storage-path: release
  package-name: ${{inputs.package-name}}${{github.event.inputs.package-name}}
  dist-dir: dist
  bcompiler-dir: compiler
  host_jobs: $J

jobs:
  build:
    runs-on: [self-hosted]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{github.event.inputs.branch}}
      - name: Env setup
        id: host
        shell: bash
        run: |
          echo "Current host supports ${{env.host_jobs}} parallel jobs"
          echo "::set-output name=jobs::${{env.host_jobs}}"
      - name: Download compilers
        shell: bash
        run: |
          set -e
          export XZ_OPT='-T0'

          inflate() {
            echo "Installing $1"
            case $1 in
              clang-12 )
                wget https://github.com/llvm/llvm-project/releases/download/llvmorg-12.0.1/clang+llvm-12.0.1-x86_64-linux-gnu-ubuntu-16.04.tar.xz -nv -O - | tar -C $2 -xJf - &
                ;;
              clang-11 )
                wget https://github.com/llvm/llvm-project/releases/download/llvmorg-11.1.0/clang+llvm-11.1.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz -nv -O - | tar -C $2 -xJf - &
                ;;
              clang-10 )
                wget https://github.com/llvm/llvm-project/releases/download/llvmorg-10.0.1/clang+llvm-10.0.1-x86_64-linux-gnu-ubuntu-16.04.tar.xz -nv -O - | tar -C $2 -xJf - &
                ;;
              clang-9 )
                wget https://github.com/llvm/llvm-project/releases/download/llvmorg-9.0.1/clang+llvm-9.0.1-x86_64-linux-gnu-ubuntu-16.04.tar.xz -nv -O - | tar -C $2 -xJf - &
                ;;
              clang-8 )
                wget https://releases.llvm.org/8.0.0/clang+llvm-8.0.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz -nv -O - | tar -C $2 -xJf - &
                ;;
              clang-7 )
                wget https://releases.llvm.org/7.0.1/clang+llvm-7.0.1-x86_64-linux-gnu-ubuntu-16.04.tar.xz -nv -O - | tar -C $2 -xJf - &
                ;;
              clang-6 )
                wget https://releases.llvm.org/6.0.1/clang+llvm-6.0.1-x86_64-linux-gnu-ubuntu-16.04.tar.xz -nv -O - | tar -C $2 -xJf - &
                ;;
              clang-5 )
                wget https://releases.llvm.org/5.0.2/clang+llvm-5.0.2-x86_64-linux-gnu-ubuntu-16.04.tar.xz -nv -O - | tar -C $2 -xJf - &
                ;;
              clang-4 )
                wget https://releases.llvm.org/4.0.0/clang+llvm-4.0.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz -nv -O - | tar -C $2 -xJf - &
                ;;
              gcc-4.5 )
                wget ${{env.compilers-dist-url}}/gcc-4.5-bambu-Ubuntu_16.04.tar.xz --no-check-certificate -nv -O - | tar -C $2 -xJf - 
                ;;
              gcc-4.6 )
                wget ${{env.compilers-dist-url}}/gcc-4.6-bambu-Ubuntu_16.04.tar.xz --no-check-certificate -nv -O - | tar -C $2 -xJf - 
                ;;
              gcc-4.7 )
                wget ${{env.compilers-dist-url}}/gcc-4.7-bambu-Ubuntu_16.04.tar.xz --no-check-certificate -nv -O - | tar -C $2 -xJf - 
                ;;
              gcc-4.8 )
                wget ${{env.compilers-dist-url}}/gcc-4.8-bambu-Ubuntu_16.04.tar.xz --no-check-certificate -nv -O - | tar -C $2 -xJf - 
                ;;
              gcc-4.9 )
                wget ${{env.compilers-dist-url}}/gcc-4.9-bambu-Ubuntu_16.04.tar.xz --no-check-certificate -nv -O - | tar -C $2 -xJf - 
                ;;
              gcc-5 )
                wget ${{env.compilers-dist-url}}/gcc-5-bambu-Ubuntu_16.04.tar.xz --no-check-certificate -nv -O - | tar -C $2 -xJf - 
                ;;
              gcc-6 )
                wget ${{env.compilers-dist-url}}/gcc-6-bambu-Ubuntu_16.04.tar.xz --no-check-certificate -nv -O - | tar -C $2 -xJf - 
                ;;
              gcc-7 )
                wget ${{env.compilers-dist-url}}/gcc-7-bambu-Ubuntu_16.04.tar.xz --no-check-certificate -nv -O - | tar -C $2 -xJf - 
                ;;
              gcc-8 )
                wget ${{env.compilers-dist-url}}/gcc-8-bambu-Ubuntu_16.04.tar.xz --no-check-certificate -nv -O - | tar -C $2 -xJf - 
                ;;
              * )
                echo "Unknown compiler required"
                exit 1
                ;;
            esac
          } 
          IFS=',' read -r -a compilers <<< "${{env.compilers}}"
          compilers=( $(IFS=$'\n'; echo "${compilers[*]}" | sort -V) )
          mkdir ${{env.dist-dir}}
          for compiler in "${compilers[@]}"
          do
            inflate $compiler ${{env.dist-dir}}
          done
          wait
          if [[ ! -z "${{env.build-compiler}}" ]]
          then
            mkdir ${{env.bcompiler-dir}}
            inflate ${{env.build-compiler}} ${{env.bcompiler-dir}}
          fi
          wait
      - name: Build Bambu application
        id: build
        uses: ./.github/actions/generate-bin
        with:
          config-args: ${{env.configure}} --enable-Werror
          jobs: ${{steps.host.outputs.jobs}}
      - name: Upload PandA Bambu HLS AppImage for CI
        if: ${{ inputs.package-name != "" }}
        uses: ./.github/actions/storage-upload
        with:
          name: ${{env.package-name}}
          path: ${{steps.build.outputs.appimage}}
          storage-url: ${{env.storage-url}}
          username: "${{env.storage-user}}"
          password: "${{env.storage-token}}"
          storage-compression: false
      - name: Upload Panda Bambu HLS Release
        if: ${{ github.event.inputs.package-name != "" }}
        shell: bash
        run: |
          APP_FILE="${{env.package-name}}.AppImage"
          STORAGE_URL="${{env.storage-url}}/${{env.storage-path}}/$APP_FILE"
          curl -L --fail -u '${{env.storage-user}}':'${{env.storage-token}}' -T "${{steps.build.outputs.appimage}}" "$STORAGE_URL"
          echo "::notice:: New release available at https://release.bambuhls.eu:8080/appimage/$APP_FILE"
