name: Build GCC

on:
  workflow_dispatch:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

env:
  storage-url: ${{secrets.CI_STORAGE_URL}}
  storage-user: ${{secrets.CI_STORAGE_USER}}
  storage-token: ${{secrets.CI_STORAGE_TOKEN}}
  storage-path: compilers

jobs:
  build:
    runs-on: [self-hosted]
    strategy:
      matrix:
        version: ['5', '6', '7', '8']
      fail-fast: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build GCC-${{matrix.version}}
        id: build
        uses: ./.github/actions/build-gcc
        with:
          branch: releases/gcc-${{matrix.version}}
          dist-name: gcc-${{matrix.version}}-bambu
          config-args: -v --with-pkgversion="Ubuntu ${{matrix.version}}-bambu" --with-bugurl="file:///usr/share/doc/gcc-${{matrix.version}}/README.Bugs" --enable-languages=c,c++,fortran --prefix=/usr --program-suffix=-${{matrix.version}} --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --with-system-zlib --disable-browser-plugin --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
      - name: Upload GCC-${{matrix.version}} dist directory
        uses: ./.github/actions/storage-upload
        with:
          path: ${{steps.build.outputs.dist-dir}}/.
          storage-url: '${{env.storage-url}}'
          storage-path: '${{env.storage-path}}'
          username: '${{env.storage-user}}'
          password: '${{env.storage-token}}'
