name: Build

on:
  workflow_dispatch:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

env:
  build-args: --enable-glpk --enable-flopoco --enable-opt --with-opt-level=2 --enable-release
  dist-pkg: bambu
  storage-url: ${{secrets.CI_STORAGE_URL}}
  storage-user: '${{secrets.CI_STORAGE_USER}}'
  storage-token: '${{secrets.CI_STORAGE_TOKEN}}'

jobs:
  build:
    runs-on: [self-hosted]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Prepare ccache timestamp
        id: ccache_cache_timestamp
        shell: bash
        run: |
          echo "::set-output name=timestamp::$(date -u +'%Y-%m-%d-%H;%M;%S')"
      - name: ccache cache files
        uses: actions/cache@v2
        with:
          path: .ccache
          key: panda-build-ccache-${{ steps.ccache_cache_timestamp.outputs.timestamp }}
          restore-keys: |
            panda-build-ccache-
      - name: Download clang compilers
        shell: bash
        run: |
          mkdir dist
          wget https://github.com/llvm/llvm-project/releases/download/llvmorg-11.1.0/clang+llvm-11.1.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz -q -O - | pxz -dc | tar -C dist -xf - &
          wget https://releases.llvm.org/7.0.1/clang+llvm-7.0.1-x86_64-linux-gnu-ubuntu-16.04.tar.xz -q -O - | pxz -dc | tar -C dist -xf - &
          wget https://releases.llvm.org/6.0.1/clang+llvm-6.0.1-x86_64-linux-gnu-ubuntu-16.04.tar.xz -q -O - | pxz -dc | tar -C dist -xf - &
          wget https://releases.llvm.org/5.0.2/clang+llvm-5.0.2-x86_64-linux-gnu-ubuntu-16.04.tar.xz -q -O - | pxz -dc | tar -C dist -xf - &
          wget https://releases.llvm.org/4.0.0/clang+llvm-4.0.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz -q -O - | pxz -dc | tar -C dist -xf - &
          wait
      - name: Download gcc 4.9
        uses: ./.github/actions/storage-download
        with:
          name: gcc-4.9-bambu-Ubuntu_16.04
          path: ./dist
          storage-url: '${{env.storage-url}}'
          storage-path: compilers
          username: '${{env.storage-user}}'
          password: '${{env.storage-token}}'
      - name: Download gcc 5
        uses: ./.github/actions/storage-download
        with:
          name: gcc-5-bambu-Ubuntu_16.04
          path: ./dist
          storage-url: '${{env.storage-url}}'
          storage-path: compilers
          username: '${{env.storage-user}}'
          password: '${{env.storage-token}}'
      - name: Download gcc 6
        uses: ./.github/actions/storage-download
        with:
          name: gcc-6-bambu-Ubuntu_16.04
          path: ./dist
          storage-url: '${{env.storage-url}}'
          storage-path: compilers
          username: '${{env.storage-user}}'
          password: '${{env.storage-token}}'
      - name: Download gcc 7
        uses: ./.github/actions/storage-download
        with:
          name: gcc-7-bambu-Ubuntu_16.04
          path: ./dist
          storage-url: '${{env.storage-url}}'
          storage-path: compilers
          username: '${{env.storage-user}}'
          password: '${{env.storage-token}}'
      - name: Download gcc 8
        uses: ./.github/actions/storage-download
        with:
          name: gcc-8-bambu-Ubuntu_16.04
          path: ./dist
          storage-url: '${{env.storage-url}}'
          storage-path: compilers
          username: '${{env.storage-user}}'
          password: '${{env.storage-token}}'
      - name: Build Bambu application
        id: build
        uses: ./.github/actions/generate-bin
        with:
          config-args: ${{env.build-args}} CC=gcc-8 CXX=g++-8 --with-clang4=/clang+llvm-4*/bin/clang --with-clang5=/clang+llvm-5*/bin/clang --with-clang6=/clang+llvm-6*/bin/clang --with-clang7=/clang+llvm-7*/bin/clang --with-clang11=/clang+llvm-11*/bin/clang
      - name: Upload Panda install directory
        uses: ./.github/actions/storage-upload
        with:
          name: ${{env.dist-pkg}}
          path: ${{steps.build.outputs.appimage}}
          storage-url: '${{env.storage-url}}'
          username: '${{env.storage-user}}'
          password: '${{env.storage-token}}'
