name: Merge Pull Request
on:
  pull_request:
    types: [closed]

env:
  storage-url: ${{secrets.CI_STORAGE_URL}}
  storage-user: ${{secrets.CI_STORAGE_USER}}
  storage-token: ${{secrets.CI_STORAGE_TOKEN}}

jobs:
  remove-dist:
    runs-on: [self-hosted]
    env:
      pr_url: ${{env.storage-url}}/${{github.head_ref}}
    steps:
      - name: Remove PR storage directory
        shell: bash
        run: |
          AUTH=''
          if [[ ! -z '${{env.storage-user}}' ]]; then
            AUTH='-u ${{env.storage-user}}:${{env.storage-token}} '
          fi
          curl -L -X DELETE $AUTH "${{env.pr_url}}/"
  update-results:
    if: github.event.pull_request.merged == true
    runs-on: [self-hosted]
    env:
      pr_url: ${{env.storage-url}}/results/${{github.head_ref}}
      base_url: ${{env.storage-url}}/results/${{github.base_ref}}
    steps:
      - name: Update base branch performance results
        shell: bash
        run: |
          AUTH=''
          if [[ ! -z '${{env.storage-user}}' ]]; then
            AUTH='-u ${{env.storage-user}}:${{env.storage-token}} '
          fi
          curl -L -X MOVE $AUTH --header "Destination:${{env.base_url}}/" "${{env.pr_url}}/"
          curl -L -X DELETE $AUTH "${{env.pr_url}}/"
